# Generated by Django 3.2 on 2021-04-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=15)),
                ('Task_Discription', models.CharField(max_length=50)),
                ('Created_Time', models.DateTimeField(auto_now_add=True)),
                ('Updated_Time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
